package com.example.nubusaploy.snapmemory.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by jutarat on 7/8/2016.
 */
public class Other_people extends RealmObject {
    @PrimaryKey
    private int other_people_id;

    private String  other_people_name;
    private int user_id;

    // Standard getters & setters generated by your IDE…


    public int getOther_people_id() {return other_people_id;}

    public void setOther_people_id(int other_people_id) {this.other_people_id = other_people_id;}

    public void setOther_people_name(String other_people_name) {this.other_people_name = other_people_name;}

    public String getOther_people_name() {return other_people_name;}

    public void setUser_id(int user_id) {this.user_id = user_id;}

    public int getUser_id() {return user_id;}
}
