package com.example.nubusaploy.snapmemory.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by jutarat on 7/8/2016.
 */
public class Other_activity extends RealmObject {
    @PrimaryKey
    private int other_activity_id;

    private String  other_activity_name;
    private int user_id;
    private int image_id;

    // Standard getters & setters generated by your IDE…


    public int getOther_activity_id() {return other_activity_id;}

    public void setOther_activity_id(int other_activity_id) {this.other_activity_id = other_activity_id;}

    public void setOther_activity_name(String other_activity_name) {this.other_activity_name = other_activity_name;}

    public String getOther_activity_name() {return other_activity_name;}

    public void setUser_id(int user_id) {this.user_id = user_id;}

    public int getUser_id() {return user_id;}

    public int getImage_id() {return image_id;}

    public void setImage_id(int image_id) {this.image_id = image_id;}
}
